# Generated by Django 5.2.8 on 2025-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninterest',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
    ]
