# Generated by Django 5.2.8 on 2025-11-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
    ]
