# Generated by Django 5.2.8 on 2025-12-04 07:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_loaninterest_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1000'))]),
        ),
    ]
